### ISSUE TITLE
Update to 1.0.3 seems to have broken Temperature and Target Temperature

### ISSUE THREAD

**Issue by daneedk** [athombv/nl.eneco.toon#6] opened 2017-01-26 14:29 UTC
My Toon app was automatically updated to 1.0.3 and since then I am not getting any new information for Temperature and Target Temperature, it's 'stuck' on the last saved values.

<img width="1256" alt="schermafbeelding 2017-01-26 om 15 25 33" src="https://cloud.githubusercontent.com/assets/16610696/22334758/39705a1c-e3dc-11e6-940e-994eebf13b71.png">

**Comment by RobinBol** [comment] 2017-02-22 13:26
This is probably caused by the Toon API not responding, the app is released as beta because the Toon API is not as reliable as we'd like. Hopefully this will change in the future.

**Closed by RobinBol** 2017-02-22 13:26 UTC
